# Generated by Django 5.1.6 on 2025-02-27 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0010_alter_favorite_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(default='Enter measurement', max_length=50),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipeApp.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_portion',
            field=models.CharField(default='1 serving', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('recipe', 'ingredient_name')},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('user', 'recipe_name')},
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
