# Generated by Django 5.1.6 on 2025-02-27 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0011_ingredient_measure_ingredient_recipe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instruction',
            unique_together={('recipe', 'step_no')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'recipe')},
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='image',
        ),
    ]
