# Generated by Django 5.1.6 on 2025-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0013_category_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
